elasticsearch_helper_content.index.*:
  type: config_entity
  label: 'Elasticsearch content index config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    entity_type:
      type: string
      label: 'Entity type'
    bundle:
      type: string
      label: 'Bundle'
    normalizer:
      type: string
      label: 'Entity normalizer'
    normalizer_configuration:
      type: sequence
      label: 'Entity normalizer configuration'

views.filter.elasticsearch_index:
  type: views.filter.in_operator
